import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "fs";
import { dirname, resolve, sep } from "path";
import { fileURLToPath } from "url";

const lifecycleDir = dirname(fileURLToPath(import.meta.url));
const agentDir = process.env.GSTACK_INTELLIGENCE_DIR
  ? resolve(process.env.GSTACK_INTELLIGENCE_DIR)
  : resolve(lifecycleDir, "..");
const skillsDir = resolve(agentDir, "skills");
const referencesDir = resolve(skillsDir, "references");
const sourceRepo = process.env.GSTACK_SOURCE_REPO ?? "garrytan/gstack";
const sourceRef = process.env.GSTACK_SOURCE_REF ?? "main";
const sourceMetadataPath = resolve(skillsDir, "source.json");

const SOURCE_FILES = {
  ethos: "ETHOS.md",
  architecture: "ARCHITECTURE.md",
  agents: "AGENTS.md",
  reviewTemplate: "review/SKILL.md.tmpl",
  reviewChecklist: "review/checklist.md",
  reviewDesignChecklist: "review/design-checklist.md",
  csoTemplate: "cso/SKILL.md.tmpl",
  csoAcknowledgements: "cso/ACKNOWLEDGEMENTS.md",
};

function rawUrl(path: string) {
  return `https://raw.githubusercontent.com/${sourceRepo}/${sourceRef}/${path}`;
}

function gitHubApiUrl(path: string) {
  return `https://api.github.com/repos/${sourceRepo}/${path}`;
}

function requestHeaders() {
  const headers: Record<string, string> = {
    "User-Agent": "github-gstack-intelligence-refresh",
    "Accept": "application/vnd.github+json",
  };

  if (process.env.GITHUB_TOKEN) {
    headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  }

  return headers;
}

async function fetchText(path: string): Promise<string> {
  console.log(`Fetching ${path} from ${sourceRepo}@${sourceRef}`);
  const response = await fetch(rawUrl(path), { headers: requestHeaders() });

  if (!response.ok) {
    throw new Error(`Failed to fetch ${path}: ${response.status} ${response.statusText}`);
  }

  return await response.text();
}

async function fetchSourceCommit(): Promise<string | null> {
  const response = await fetch(gitHubApiUrl(`commits/${sourceRef}`), { headers: requestHeaders() });

  if (!response.ok) {
    console.warn(
      `Could not resolve source commit for ${sourceRepo}@${sourceRef}: ` +
      `${response.status} ${response.statusText}. Recording the configured ref only.`,
    );
    return null;
  }

  const payload = await response.json();
  return payload.sha ?? null;
}

function ensureDir(path: string) {
  mkdirSync(path, { recursive: true });
}

function writeFile(path: string, content: string) {
  ensureDir(dirname(path));
  writeFileSync(path, content.endsWith("\n") ? content : `${content}\n`, "utf-8");
}

function resolveManagedOutput(relativePath: string) {
  const absolutePath = resolve(agentDir, relativePath);
  const managedRoot = `${agentDir}${sep}`;

  if (absolutePath !== agentDir && !absolutePath.startsWith(managedRoot)) {
    throw new Error(`Refusing to access output outside ${agentDir}: ${relativePath}`);
  }

  return absolutePath;
}

function readPreviousOutputs(): string[] {
  if (!existsSync(sourceMetadataPath)) {
    return [];
  }

  try {
    const payload = JSON.parse(readFileSync(sourceMetadataPath, "utf-8")) as { outputs?: unknown };
    return Array.isArray(payload.outputs)
      ? payload.outputs.filter((value): value is string => typeof value === "string")
      : [];
  } catch (error) {
    console.warn(`Could not read previous source metadata from ${sourceMetadataPath}.`, error);
    return [];
  }
}

function removeStaleOutputs(previousOutputs: string[], currentOutputs: string[]) {
  const currentOutputSet = new Set(currentOutputs);

  for (const relativePath of previousOutputs) {
    if (currentOutputSet.has(relativePath)) {
      continue;
    }

    const absolutePath = resolveManagedOutput(relativePath);

    if (existsSync(absolutePath)) {
      rmSync(absolutePath, { force: true });
      console.log(`Removed stale generated output ${relativePath}`);
    }
  }
}

function assertOutputsExist(outputs: string[]) {
  const missingOutputs = outputs.filter((relativePath) => !existsSync(resolveManagedOutput(relativePath)));

  if (missingOutputs.length > 0) {
    throw new Error(`Refresh completed without writing expected outputs: ${missingOutputs.join(", ")}`);
  }
}

function removeAskUserQuestionFromFrontmatter(content: string): string {
  return content.replace(/^  - AskUserQuestion\n/gm, "");
}

function replaceAll(content: string, replacements: Array<[string, string]>): string {
  return replacements.reduce(
    (next, [searchValue, replacementValue]) => next.replaceAll(searchValue, replacementValue),
    content,
  );
}

function buildGeneratedHeader(skillName: string, sourcePath: string, sourceCommit: string | null): string {
  const sourceMarker = sourceCommit
    ? `\`${sourceCommit.slice(0, 12)}\``
    : `ref \`${sourceRef}\``;
  return [
    "<!--",
    "GENERATED FILE — imported from gstack during run-refresh-gstack.",
    "Do not edit this file unless you intentionally forfeit clean upgrades and re-imports.",
    "-->",
    "",
    "> [!NOTE]",
    `> Generated by \`.github-gstack-intelligence/lifecycle/refresh.ts\`.`,
    `> Source: \`${sourceRepo}\` @ ${sourceMarker} from \`${sourcePath}\`.`,
    "> This copy is adapted for GitHub-native execution and refresh-time extraction.",
    "> Do not edit this file unless you intentionally forfeit clean upgrades and re-imports.",
    "> Re-run `run-refresh-gstack` to pull upstream gstack changes back into this repository.",
    "",
    "## GitHub-native execution notes",
    "",
    `- This is the extracted \`/${skillName}\` skill prompt committed into the repository at refresh time.`,
    "- Inject GitHub workflow context directly in the invoking lifecycle code instead of relying on local preamble expansion.",
    "- Replace interactive approval steps with issue or pull-request comments plus a follow-up GitHub event.",
    "- Use repository-local reference files under `.github-gstack-intelligence/skills/references/` instead of `~/.claude/skills/...` paths.",
    "",
  ].join("\n");
}

function buildImportedDocumentHeader(sourcePath: string, sourceCommit: string | null): string {
  const sourceMarker = sourceCommit
    ? `\`${sourceCommit.slice(0, 12)}\``
    : `ref \`${sourceRef}\``;
  return [
    "<!--",
    "GENERATED FILE — imported from gstack during run-refresh-gstack.",
    "Do not edit this file unless you intentionally forfeit clean upgrades and re-imports.",
    "-->",
    "",
    "> [!CAUTION]",
    `> Imported from \`${sourceRepo}\` @ ${sourceMarker} from \`${sourcePath}\`.`,
    "> Do not edit this file unless you intentionally forfeit clean upgrades and re-imports.",
    "> Re-run `run-refresh-gstack` to copy upstream gstack changes back into this repository.",
    "",
  ].join("\n");
}

function wrapImportedMarkdown(content: string, sourcePath: string, sourceCommit: string | null): string {
  return `${buildImportedDocumentHeader(sourcePath, sourceCommit)}${content}`;
}

function assertNoTemplateTokens(skillName: string, content: string) {
  const unresolved = [...content.matchAll(/\{\{[A-Z0-9_-]+\}\}/g)].map((match) => match[0]);

  if (unresolved.length > 0) {
    throw new Error(`Unresolved template tokens remain in ${skillName}: ${unresolved.join(", ")}`);
  }
}

function adaptReviewSkill(template: string, sourceCommit: string | null): string {
  const withoutAskUserQuestion = removeAskUserQuestionFromFrontmatter(template);
  const withDirectReplacements = replaceAll(withoutAskUserQuestion, [
    ["{{PREAMBLE}}", buildGeneratedHeader("review", SOURCE_FILES.reviewTemplate, sourceCommit)],
    ["{{BASE_BRANCH_DETECT}}", "Use the GitHub event payload, checked-out refs, and repository default branch to determine the review base branch."],
    ["{{PLAN_COMPLETION_AUDIT_REVIEW}}", "If planning artifacts are unavailable, treat the issue body, pull request body, and commit history as the stated intent and continue."],
    ["{{LEARNINGS_SEARCH}}", "Search repository-local state and issue context first before making review recommendations."],
    ["{{CONFIDENCE_CALIBRATION}}", "Use the same confidence bar, but report through GitHub comments and persisted state files rather than local CLI prompts."],
    ["{{DESIGN_REVIEW_LITE}}", "If frontend files changed, use `.github-gstack-intelligence/skills/references/review-design-checklist.md` as the design-review-lite source."],
    ["{{TEST_COVERAGE_AUDIT_REVIEW}}", "Use the checked-out repository diff and existing tests to reason about coverage; persist only the final GitHub-native findings."],
    ["{{ADVERSARIAL_STEP}}", "Before finalizing findings, do one adversarial pass that tries to disprove each claim using the checked-out code and current GitHub context."],
    ["{{LEARNINGS_LOG}}", "Persist durable review outcomes in `.github-gstack-intelligence/state/results/review/` when the lifecycle layer is ready to store them."],
    ["Read `.claude/skills/review/checklist.md`.", "Read `.github-gstack-intelligence/skills/references/review-checklist.md`."],
    ["use individual AskUserQuestion calls instead of batching.", "use individual GitHub follow-up comments instead of batching."],
    ["AskUserQuestion", "GitHub follow-up comment"],
    ["~/.claude/skills/gstack/bin/gstack-review-log", ".github-gstack-intelligence/state/results/review/review-log.json"],
  ]);

  const withGreptileNote = withDirectReplacements.replace(
    /## Step 2\.5: Check for Greptile review comments[\s\S]*?## Step 3: Get the diff/,
    [
      "## Step 2.5: Check for GitHub review signals",
      "",
      "If the repository has existing review comments or automation findings, treat them as supplemental inputs.",
      "Skip silently when none are available. The extracted skill must remain runnable without local Greptile integration.",
      "",
      "## Step 3: Get the diff",
    ].join("\n"),
  );

  assertNoTemplateTokens("review", withGreptileNote);
  return withGreptileNote;
}

function adaptCsoSkill(template: string, sourceCommit: string | null): string {
  const withoutAskUserQuestion = removeAskUserQuestionFromFrontmatter(template);
  const adapted = replaceAll(withoutAskUserQuestion, [
    ["{{PREAMBLE}}", buildGeneratedHeader("cso", SOURCE_FILES.csoTemplate, sourceCommit)],
    ["{{CONFIDENCE_CALIBRATION}}", "Use the same confidence-gated reporting thresholds, but publish the final posture report through GitHub comments and repository-local state instead of local CLI interactions."],
    ["AskUserQuestion", "GitHub follow-up comment"],
    ['"Phase 8 can scan your globally installed AI coding agent skills and hooks for malicious patterns. This reads files outside the repo. Want to include this?"', '"Phase 8 can scan globally installed AI coding agent skills and hooks for malicious patterns. Post a GitHub follow-up comment asking for approval before reading files outside the repo."'],
  ]);

  assertNoTemplateTokens("cso", adapted);
  return adapted;
}

async function main() {
  const sourceCommit = await fetchSourceCommit();
  const generatedAt = new Date().toISOString();
  const sourceMarker = sourceCommit ?? `ref ${sourceRef}`;

  console.log(`Refreshing gstack resources from ${sourceRepo} (${sourceMarker})`);

  const [
    ethos,
    architecture,
    agents,
    reviewTemplate,
    reviewChecklist,
    reviewDesignChecklist,
    csoTemplate,
    csoAcknowledgements,
  ] = await Promise.all([
    fetchText(SOURCE_FILES.ethos),
    fetchText(SOURCE_FILES.architecture),
    fetchText(SOURCE_FILES.agents),
    fetchText(SOURCE_FILES.reviewTemplate),
    fetchText(SOURCE_FILES.reviewChecklist),
    fetchText(SOURCE_FILES.reviewDesignChecklist),
    fetchText(SOURCE_FILES.csoTemplate),
    fetchText(SOURCE_FILES.csoAcknowledgements),
  ]);

  ensureDir(skillsDir);
  ensureDir(referencesDir);

  const managedOutputs = [
    {
      path: "ETHOS.md",
      content: wrapImportedMarkdown(ethos, SOURCE_FILES.ethos, sourceCommit),
    },
    {
      path: "skills/references/gstack-architecture.md",
      content: wrapImportedMarkdown(architecture, SOURCE_FILES.architecture, sourceCommit),
    },
    {
      path: "skills/references/gstack-agents.md",
      content: wrapImportedMarkdown(agents, SOURCE_FILES.agents, sourceCommit),
    },
    {
      path: "skills/references/review-checklist.md",
      content: wrapImportedMarkdown(reviewChecklist, SOURCE_FILES.reviewChecklist, sourceCommit),
    },
    {
      path: "skills/references/review-design-checklist.md",
      content: wrapImportedMarkdown(reviewDesignChecklist, SOURCE_FILES.reviewDesignChecklist, sourceCommit),
    },
    {
      path: "skills/references/cso-acknowledgements.md",
      content: wrapImportedMarkdown(csoAcknowledgements, SOURCE_FILES.csoAcknowledgements, sourceCommit),
    },
    {
      path: "skills/review.md",
      content: adaptReviewSkill(reviewTemplate, sourceCommit),
    },
    {
      path: "skills/cso.md",
      content: adaptCsoSkill(csoTemplate, sourceCommit),
    },
  ] as const;
  const outputPaths = managedOutputs.map((output) => output.path);

  removeStaleOutputs(readPreviousOutputs(), outputPaths);

  for (const output of managedOutputs) {
    writeFile(resolveManagedOutput(output.path), output.content);
  }

  assertOutputsExist(outputPaths);

  writeFile(
    sourceMetadataPath,
    JSON.stringify(
      {
        extractedAt: generatedAt,
        source: {
          repo: sourceRepo,
          ref: sourceRef,
          commit: sourceCommit,
        },
        inputs: Object.values(SOURCE_FILES),
        outputs: outputPaths,
      },
      null,
      2,
    ),
  );

  console.log("Refresh complete.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
